apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  {{- if .Values.networking.clusterIP }}
  clusterIP: {{ .Values.networking.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.networking.rapidsai.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.spark.sparkui }}
    - port: {{ .Values.networking.sparkui.port }}
      targetPort: 4040
      protocol: TCP
      name: sparkui
    {{- end }}
  selector:
    {{- include "library-chart.selectorLabels" . | nindent 4 }}
