apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
data:
  delta-sharing-server-config.yaml: |
    # The format version of this config file
    version: 1
    # Config shares/schemas/tables to share
    {{ printf "%s:" "shares" }}
    {{- range $.Values.shares }}
    {{ printf "- %s: %s" "name" (.name | quote) }}
    {{ printf "%s: " "schemas" | indent 2 }}
    {{- range .schemas }}
    {{ printf "- %s: %s" "name" (.name | quote) | indent 2 }}
    {{ printf "%s: " "tables" | indent 4 }}
    {{- range .tables }}
    {{ printf "- %s: %s" "name" (.name | quote) | indent 4 }}
    {{ printf "%s: %s" "location" .location | indent 6 }}
    {{- end }} 
    {{- end }} 
    {{- end }} 
    
    # Set the host name that the server will use
    host: {{ .Values.ingress.hostname | quote }}
    # Set the port that the server will listen on. Note: using ports below 1024 
    # may require a privileged user in some operating systems.
    port: 8080
    # Set the url prefix for the REST APIs
    endpoint: "/delta-sharing"
    # Set the timeout of S3 presigned url in seconds
    preSignedUrlTimeoutSeconds: 3600
    # How many tables to cache in the server
    deltaTableCacheSize: 10
    # Whether we can accept working with a stale version of the table. This is useful when sharing
    # static tables that will never be changed.
    stalenessAcceptable: false
    # Whether to evaluate user provided `predicateHints`
    evaluatePredicateHints: false