{{- if .Values.sidecar.proxy.subrequest.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library-chart.fullname" . }}-nginx
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
data:
  nginx.conf: |
    error_log /dev/stdout info;
    events {
    worker_connections  4096;
    }

    http {
        
        server {
            listen 80;

            location / {
                auth_request     /auth;
                auth_request_set $auth_status $upstream_status;
                proxy_pass http://localhost:8080;
            }

            location = /auth {
                internal;
                proxy_pass              {{ .Values.sidecar.proxy.subrequest.authService }};
                proxy_pass_request_body off;
                proxy_set_header        Content-Length "";
                proxy_set_header        X-Original-URI $request_uri;
                proxy_set_header        Authorization $http_authorization; 
            }
        }
    }
{{- end -}}