apiVersion: v1
kind: Secret
metadata:
  name: redash-postgres
type: Opaque
data:
  connectionString: {{ printf "postgresql://%s:%s@%s:5432/%s" .Values.global.postgresql.postgresqlUsername .Values.global.postgresql.postgresqlPassword .Values.postgresql.fullnameOverride .Values.global.postgresql.postgresqlDatabase| b64enc | quote }}