apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-chart.fullname" . }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  {{- if .Values.networking.clusterIP }}
  clusterIP: {{ .Values.networking.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.networking.tensorflow.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.tensorboard }}
    - port: {{ .Values.networking.tensorboard.port }}
      targetPort: 6006
      protocol: TCP
      name: tensorboard
    {{- end }}
  selector:
    {{- include "library-chart.selectorLabels" . | nindent 4 }}
